### ISSUE TITLE
Lintr issue in R notebook files

### ISSUE THREAD

**Issue by j-huic** [REditorSupport/vscode-R#1198]
So I followed [this](https://www.practicaldatascience.org/html/jupyter_r_notebooks.html) to get an R notebook running in VS Code (steps 2-4 since I had Jupyter and R already installed). The code in the notebook runs fine, but I keep getting the following error in random places:

```
"Failed to run diagnostics: callr subprocess failed: Full file exclusions must be character vectors of length 1. items: 1 are not! lintr"
```

I guess it comes up wherever there is supposed to be a style correction, and it comes up if I make other intentional style errors, like using "=" for assignment instead of "<-". For instance, running lint( ) on this same file returns the following (along with a bunch of other style corrections):
```
style: [brace_linter] Opening curly braces should never go on their own line and should always be followed by a new line.
{

error: [error] unexpected '['
 "cells": [
          ^

style: [line_length_linter] Lines should not be more than 80 characters.

\u001b[22m\u001b[34mstyle: \u001b[39m[brace_linter] \u001b[1mOpening curly braces should never go on their own line and should always be followed by a new line.\u001b[22m\n",
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I do have a .lintr file in my directory, but I had to create one with use_lintr( ) as per [this link](https://lintr.r-lib.org/articles/lintr.html).  The error existed previous to creating this file. Running read.dcf(".lintr") returns this (as a table):

```
linters	encoding
linters_with_defaults() # see vignette("lintr")	"UTF-8"
```

This issue does not appear with the R extension disabled, but that's a poor solution since I definitely want its provided features. It also does not appear when I remove the languageserver package but again, I lose intellisense.

**Environment**:
- OS: Windows
- Version: 1.71.1 (user setup)
Commit: e7f30e38c5a4efafeec8ad52861eb772a9ee4dfb
Date: 2022-09-08T19:56:36.424Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No
- R Version: 4.2.0
- vscode-R version: 2.5.3

**Additional context**

The lint(".currentfile") output was extra confusing because:
1. I don't think the curly braces error refers to my function, since it comes up even without any functions in the file
2. The second error calls a square bracket out of place, while there are no square brackets in the file
3. The third error (and a ton of similar ones below it) refer to lines of 80+ characters, when my entire notebook file is three chunks:

I think it's best if I just paste the screenshot here:
![image](https://user-images.githubusercontent.com/71459066/190274800-28b4509b-08a7-4f34-8a0c-a5cfc6946516.png)
There's another two screens worth of messages - after the screenshot runs out, they refer to every single line 52-72 (**even though these three chunks are the entire file**)

Here's a text file with the whole error message:
[errormsg_ipynb.txt](https://github.com/REditorSupport/vscode-R/files/9570416/errormsg_ipynb.txt)

Regular .R files in the same directory work fine, it is only the notebook files.
I don't think I have an R project set up, since there is no .Rproj file (although I can still use relative paths for files in the same folder), and the parent folder is also the working directory for which I used setwd(). I have no idea how much this matters, but I guess the extra info can't hurt, and I also got `['${workspaceFolder}' can not be resolved` from VS Code while I was setting up the extension and the languageserver package, although I opened the workspace folder in VS Code and everything was fine afterwards.

Let me know if I can provide additional info, thanks.

**Comment by pgcudahy** [comment]
I'm getting a similar issue

I have the REditorSupport extension installed in VScode and the `languageserver` package installed in R. When I enter code in a `test.r` file in VScode, it is linted as expected. 

`a<- 1 + 2`

```
[{
	"resource": "/Users/pgcudahy/test.r",
	"owner": "_generated_diagnostic_collection_name_#4",
	"severity": 2,
	"message": "Put spaces around all infix operators.",
	"source": "infix_spaces_linter",
	"startLineNumber": 1,
	"startColumn": 2,
	"endLineNumber": 1,
	"endColumn": 4
}]
```

But when I try the same code in a `test.ipynb` jupyter notebook within vscode, the linter complains with

`a<- 1 + 2`

```
[{
	"resource": "/Users/pgcudahy/test.ipynb",
	"owner": "_generated_diagnostic_collection_name_#6",
	"severity": 8,
	"message": "Failed to run diagnostics: ! error in callr subprocess\nCaused by error: \n! Full file exclusions must be character vectors of length 1. items: 1 are not!",
	"source": "lintr",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 1
}]
```
Uninstalling the `languageserver` package removes the error, but then the code is not linted.

## Logs

```
[I 14:44:26.944 NotebookApp] Starting buffering for 88696d60-31ac-467d-853a-c9824e5616b4:59e6fee9-ae04-4afb-b900-240e1ff865e5
[W 14:44:26.947 NotebookApp] 404 GET /json/list (127.0.0.1) 1.900000ms referer=None
[W 14:44:37.172 NotebookApp] 404 GET /json/list (127.0.0.1) 1.390000ms referer=None
[W 14:44:37.229 NotebookApp] 404 GET /json/list (127.0.0.1) 1.250000ms referer=None
[W 14:44:37.286 NotebookApp] 404 GET /json/list (127.0.0.1) 1.300000ms referer=None
[W 14:44:37.343 NotebookApp] 404 GET /json/list (127.0.0.1) 1.250000ms referer=None
[W 14:44:37.402 NotebookApp] 404 GET /json/list (127.0.0.1) 1.250000ms referer=None
[W 14:44:37.460 NotebookApp] 404 GET /json/list (127.0.0.1) 1.780000ms referer=None
[W 14:44:37.519 NotebookApp] 404 GET /json/list (127.0.0.1) 1.420000ms referer=None
[W 14:44:37.576 NotebookApp] 404 GET /json/list (127.0.0.1) 0.610000ms referer=None
[W 14:44:37.632 NotebookApp] 404 GET /json/list (127.0.0.1) 0.470000ms referer=None
[W 14:44:37.686 NotebookApp] 404 GET /json/list (127.0.0.1) 1.130000ms referer=None
info 14:44:48.344: Attempting to start a server because of preload conditions ...
info 14:44:48.449: Starting Jupyter Session startUsingLocalKernelSpec, .ir./opt/homebrew/Cellar/r/4.2.2/lib/R/bin/R././opt/homebrew/cellar/r/4.2.2/lib/r/bin/r#--slave#-e#irkernel::main()#--args#{connection_file} for '/Users/pgcudahy/test.ipynb' (disableUI=true)
[I 14:44:48.452 NotebookApp] Creating new notebook in 
info 14:44:48.857: Got empty env vars with python /opt/homebrew/bin/python3.11 in 10ms
[W 14:44:59.766 NotebookApp] 404 GET /json/list (127.0.0.1) 1.090000ms referer=None
[W 14:44:59.825 NotebookApp] 404 GET /json/list (127.0.0.1) 2.350000ms referer=None
[W 14:44:59.881 NotebookApp] 404 GET /json/list (127.0.0.1) 1.060000ms referer=None
[W 14:44:59.937 NotebookApp] 404 GET /json/list (127.0.0.1) 1.990000ms referer=None
[W 14:44:59.995 NotebookApp] 404 GET /json/list (127.0.0.1) 2.170000ms referer=None
[W 14:45:00.053 NotebookApp] 404 GET /json/list (127.0.0.1) 1.680000ms referer=None
[W 14:45:00.111 NotebookApp] 404 GET /json/list (127.0.0.1) 1.650000ms referer=None
[W 14:45:00.167 NotebookApp] 404 GET /json/list (127.0.0.1) 1.650000ms referer=None
[W 14:45:00.221 NotebookApp] 404 GET /json/list (127.0.0.1) 1.480000ms referer=None
[W 14:45:00.279 NotebookApp] 404 GET /json/list (127.0.0.1) 2.420000ms referer=None
[I 14:45:02.422 NotebookApp] Kernel started: 61cf4691-dcf5-4289-a0ee-c5ff1279ae9c, name: ir
[W 14:45:02.430 NotebookApp] delete /test-jvsc-1274ee69-6e0d-4487-8bd4-9e5be4667dec7d42c400-158c-4466-9b66-fe6f988a916e.ipynb
info 14:45:03.227: Started session for kernel startUsingLocalKernelSpec:.ir./opt/homebrew/Cellar/r/4.2.2/lib/R/bin/R././opt/homebrew/cellar/r/4.2.2/lib/r/bin/r#--slave#-e#irkernel::main()#--args#{connection_file}
```

According to [this](https://stackoverflow.com/questions/72987553/anyone-know-why-lintr-is-marking-the-first-string-of-my-jupyter-r-kernels-in-red) stackoverflow question, it seems other people are having this issue too, but with base R, and not just jupyter.

I've tried it with and without .lintr files, but that doesn't seem to make a difference.

**Comment by halidaee** [comment]
I'm also having this issue with base R. I've tried re-installing VScode and R from scratch but this hasn't solved the issue. Any update?

**Comment by kdzhang** [comment]
I also have this issue, and removing `languageserver` package solves the problem. Adding `"r.lsp.diagnostics": false` to settings does not solve the problem.

**Comment by camel712** [comment]
I also have this issue.

**Comment by quimaguirre** [comment]
I have the same problem.

**Comment by lucy924** [comment]
I also have this problem

**Comment by renkun-ken** [comment]
I could reproduce this problem. Let me check out what should be done in languageserver to make it work properly for notebooks.

**Comment by renkun-ken** [comment]
https://github.com/REditorSupport/languageserver/pull/610 should fix the problem.

**Comment by renkun-ken** [comment]
Installing the latest dev of languageserver should work now.

**Comment by quimaguirre** [comment]
Works for me!

**Comment by kdzhang** [comment]
works for me as well!

**Comment by renkun-ken** [comment]
Closing as resolved.

**Comment by gonzarizzo** [comment]
Hello! Could you make the latest dev of languageserver available through conda-forge? I am still getting this error with the latest version available there (_i.e._, v0.3.15). Thank you!
