### ISSUE TITLE
Code autocomplete not working 

### ISSUE THREAD

**Issue by a-shihai** [REditorSupport/vscode-R#943]
Code autocomplete not working if the function does not have a package name in front of it, even if the package is already loaded。
![image](https://user-images.githubusercontent.com/70144885/149625294-e618ab44-88e2-4f75-8ef8-8e12b3cb64cc.png)
![image](https://user-images.githubusercontent.com/70144885/149625389-f0a60cec-d61d-4799-93c1-c489ac3f3ee4.png)

**Comment by renkun-ken** [comment]
There could be a delay between you type `library(ggplot2)` and the expected completion items appear when you type `ggplot` due to the dependency resolution is done in an async way by the background workers.

Does `ggplot` ever appear in your completion, even after a delay?

**Comment by a-shihai** [comment]
It doesn't work, even for arguments inside a function in R-4.1.2, but it  works fine in R - 4.1.0.

发件人: Kun Ren
发送时间: 2022年1月15日 22:56
收件人: REditorSupport/vscode-R
抄送: a_shihai; Author
主题: Re: [REditorSupport/vscode-R] Code autocomplete not working (Issue#943)

There could be a delay between you type library(ggplot2) and the expected completion items appear when you type ggplot due to the dependency resolution is done in an async way by the background workers.
Does ggplot ever appear in your completion, even after a delay?
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by renkun-ken** [comment]
Would you like to install the latest development version of languageserver via

```r
remotes::install_github("REditorSupport/languageserver")
```

and see if the problem still persists?

**Comment by a-shihai** [comment]
Amazing, when I install the version on hitub, it works fine, and there is also a problem, when I quit vscode, R still works in the background, is there a way to solve this problem? Thank you.
发件人: Kun Ren
发送时间: 2022年1月16日 00:12
收件人: REditorSupport/vscode-R
抄送: a_shihai; Author
主题: Re: [REditorSupport/vscode-R] Code autocomplete not working (Issue#943)

Would you like to install the latest development version of languageserver via
remotes::install_github("REditorSupport/languageserver")
and see if the problem still persists?
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by renkun-ken** [comment]
> when I install the version on hitub, it works fine

Glad to hear that it works for you.

>when I quit vscode, R still works in the background, is there a way to solve this problem

It is just resolved via #941. I'll publish a new release very soon.

**Comment by a-shihai** [comment]
Unfortunately, when I restarted vscode, it seems to be back to what it was before.

发件人: Kun Ren
发送时间: 2022年1月16日 11:24
收件人: REditorSupport/vscode-R
抄送: a_shihai; Author
主题: Re: [REditorSupport/vscode-R] Code autocomplete not working (Issue#943)

when I install the version on hitub, it works fine
Glad to hear that it works for you.
when I quit vscode, R still works in the background, is there a way to solve this problem
It is just resolved via #941. I'll publish a new release very soon.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by renkun-ken** [comment]
Which problem still exists?

**Comment by a-shihai** [comment]
> 哪个问题还存在？
Code auto-completion problem persists .  R did not exit normally has been resolved.
![image](https://user-images.githubusercontent.com/70144885/149648540-3683f6a4-d0a1-4993-93a1-ec2188a700e0.png)

**Comment by renkun-ken** [comment]
Should be a languageserver issue. I'll transfer this issue there.
